source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def import_pods
    pod 'HaishinKit', :path => '~/Documents/HaishinKit.swift/'
end

target 'LiveBroadcast'  do
    platform :ios, '11.0'
    import_pods
end
